# Bun Configuration - Platform-Native Optimization
# Only includes validated Bun configuration options

[install]
# Dependency management optimization
production = false
dev = true
peer = false  
optional = true
cache = true
registry = "https://registry.npmjs.org/"

[run]
# Script execution optimization
bun = true
shell = "system"

[build]
# Bundle optimization settings
target = "bun"
format = "esm"
minify = false
sourcemap = true
outdir = "./dist"

[test]
# Testing configuration
coverage = true
timeout = 5000
