# Praxis Configuration - Root Level
# Clean, readable YAML for project-wide settings

theme: dark
version: '1.0.0'
generation:
  outputDirectory: './generated'
  filePattern: '{name}Props.ts'
  typePrefix: 'Praxis'

# Global prop defaults
defaults:
  variant: 'primary'
  size: 'default'
  disabled: false