/**
 * Button - Migrated from TypeScript interface
 * Auto-generated by Praxis migration
 */
export default {
  "component": {
    "name": "Button",
    "description": "Migrated Button component",
    "category": "input"
  },
  "uses": {
    "variants": [
      "primary",
      "secondary",
      "danger",
      "ghost"
    ],
    "sizes": [
      "sm",
      "md",
      "lg"
    ],
    "states": [
      "disabled",
      "loading",
      "fullWidth"
    ]
  }
} as const