/**
 * Card - Migrated from TypeScript interface
 * Auto-generated by Praxis migration
 */
export default {
  "component": {
    "name": "Card",
    "description": "Migrated Card component",
    "category": "layout"
  },
  "uses": {
    "variants": [
      "outline",
      "filled",
      "elevated",
      "ghost",
      "none",
      "sm",
      "md",
      "lg"
    ],
    "sizes": [
      "sm",
      "md",
      "lg"
    ],
    "states": [
      "hoverable",
      "clickable",
      "disabled"
    ]
  }
} as const