/**
 * IconButton - Migrated from TypeScript interface
 * Auto-generated by Praxis migration
 */
export default {
  "component": {
    "name": "IconButton",
    "description": "Migrated IconButton component",
    "category": "input"
  },
  "uses": {
    "variants": [
      "solid",
      "outline",
      "ghost"
    ],
    "sizes": [
      "xs",
      "sm",
      "md",
      "lg",
      "xl"
    ],
    "states": [
      "disabled"
    ]
  }
} as const