/**
 * Input - Migrated from TypeScript interface
 * Auto-generated by Praxis migration
 */
export default {
  "component": {
    "name": "Input",
    "description": "Migrated Input component",
    "category": "input"
  },
  "uses": {
    "variants": [
      "text",
      "email",
      "password",
      "number",
      "tel",
      "url",
      "outline",
      "filled",
      "flushed",
      "unstyled"
    ],
    "sizes": [
      "xs",
      "sm",
      "md",
      "lg"
    ],
    "states": [
      "isDisabled",
      "isInvalid",
      "isRequired",
      "isReadOnly"
    ]
  }
} as const