/**
 * Modal - Migrated from TypeScript interface
 * Auto-generated by Praxis migration
 */
export default {
  "component": {
    "name": "Modal",
    "description": "Migrated Modal component",
    "category": "overlay"
  },
  "uses": {
    "variants": [
      "center",
      "top",
      "bottom"
    ],
    "sizes": [
      "sm",
      "md",
      "lg",
      "xl",
      "full"
    ],
    "states": [
      "isOpen",
      "closeOnOverlay",
      "closeOnEsc",
      "showCloseButton"
    ]
  }
} as const